### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by abovethewater** [vojtajina/grunt-coffeelint#46]
#44 Updates to include CoffeeLint ~1.1, which in turn supports CoffeeScript 1.7.
The version on npm runs an older version of CoffeeLint (1.0.8), which only supports CoffeeScript 1.6

Can the latest version please be released to npm so we can easily lint CS1.7 in our projects

Thanks

**Comment by zolzaya** [comment]
+1

**Comment by janraasch** [comment]
@zolzaya as far as I can see the latest commit on the master branch `tag v0.0.13` is live on npm: https://www.npmjs.com/package/grunt-coffeelint. This issue should be closed (cc: @adambiggs).
