### ISSUE TITLE
Strange output with interpolated strings about operator spacing

### ISSUE THREAD

**Issue by flowlo** [vojtajina/grunt-coffeelint#63]
Consider following input

```coffeescript
moo = 'meow'
foo = ' :D'
console.log "The cow says #{if moo then "#{moo}!" else ''}#{foo}"
```

with the `coffeelint.json` pasted [here](https://gist.github.com/flowlo/d8aee3e25da5da1baa61) and no special magic in `Gruntfile.coffee` and this output

```
.../bug.coffee
  ✖  line 3  Operators must be spaced properly  +
```

I see that there's some freaky string interpolation going on, but this error message is misleading.

I don't have the time to investigate where this issue is rooted. I report here because `grunt-coffelint` is the thing I'm importing.

**Comment by robhor** [comment]
The issue lies with coffeelint itself, see clutchski/coffeelint#447

**Comment by flowlo** [comment]
clutchski/coffeelint#472 looks promising, thanks @robhor
